// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default'];
    Alert: typeof import('./src/components/Alert.vue')['default'];
    AppBar: typeof import('./src/components/layout/app-bar.vue')['default'];
    AppLayout: typeof import('./src/components/layout/app-layout.vue')['default'];
    ArrowRightIcon: typeof import('./src/components/svg/arrow-right-icon.vue')['default'];
    AuthLayout: typeof import('./src/components/layout/auth-layout.vue')['default'];
    DashboardIcon: typeof import('./src/components/svg/dashboard-icon.vue')['default'];
    Dialog: typeof import('./src/components/Dialog.vue')['default'];
    Drawer: typeof import('./src/components/layout/drawer.vue')['default'];
    ElAside: typeof import('element-plus/es')['ElAside'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCard: typeof import('element-plus/es')['ElCard'];
    ElCol: typeof import('element-plus/es')['ElCol'];
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
    ElContaine: typeof import('element-plus/es')['ElContaine'];
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker'];
    ElFooter: typeof import('element-plus/es')['ElFooter'];
    ElHeader: typeof import('element-plus/es')['ElHeader'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElMai: typeof import('element-plus/es')['ElMai'];
    ElMain: typeof import('element-plus/es')['ElMain'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup'];
    ElPagination: typeof import('element-plus/es')['ElPagination'];
    ElRow: typeof import('element-plus/es')['ElRow'];
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
    ElTable: typeof import('element-plus/es')['ElTable'];
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
    Form: typeof import('./src/components/Form.vue')['default'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    Home: typeof import('./src/components/Home.vue')['default'];
    Login: typeof import('./src/components/Login.vue')['default'];
    Post: typeof import('./src/components/Post.vue')['default'];
    Table: typeof import('./src/components/Table.vue')['default'];
  }
}

export {};
